### ISSUE TITLE
Update xcode.proj please

### ISSUE THREAD

**Issue by ghost** [kainjow/ScriptQL#2]
Would you please update the `.xcodeproj` for macOS Catalina? There are some deprecated calls and I am no programmer. 

This is a very hand QL plug in and there are no others that I know of.

**Comment by kainjow** [comment]
Are you getting an error or something not working?

**Comment by jprokos** [comment]
I am a novice but, Yes. It won't build. Something about 32 bit and lots of depreciated calls.

**Comment by kainjow** [comment]
Done! Latest commit should build cleanly on Xcode 12.4.
